#*** Exercise 17.1 ----
# For the Young people survey data lets see if the answers to the Mathematics and Physics questions are related.
# Run a χ2 test between these two columns and interpret the results.
table(Young_People_Survey$Mathematics, Young_People_Survey$Physics)

chisq.test(table(Young_People_Survey$Mathematics, Young_People_Survey$Physics))

# The small p-value indicates that we should reject the null hypothesis that the are two columns are unrelated.


#* 17.3 Homework ----
#** 17.3.0.1 Concept Questions ----
# Answer the following True/False questions:
#*** 1. ----
# The χ2 test is used to determine if a relationship exists between two categorical variables
#   True


#*** 2. ----
# The χ2 test is a form of a hypothesis test with a null and alternative hypothesis.
#   True


#*** 3. ----
# If the χ2 test yields a p value above our significance threshold α we have proved that the two categorical variables have no relationship.
# False. It is failure to reject and not proved.


#*** 4. ----
# The χ2 test tells us when at least one entry in a table violates the independence assumptions but not which entry/entries are the guilty ones.
#   True


#** 17.3.0.2 Practice Problems ----
#*** 1. ----
# Load the data set quine, by running the commands library(MASS) and data(quine).
# Run a chi square test to determine if the fraction of average learners (Age=AL) is the same for all age groups.
library(MASS)
data(quine)

table(quine$Lrn, quine$Age)

chisq.test(table(quine$Lrn, quine$Age))
# The small p-value indicates that the fraction of average learners if not the same for all age groups.


#** 17.3.0.3 Advanced Problems ----
#*** 1. ----
# Random Numbers:
# The χ2 test can be used to determine if the outcomes of a random experiment are truly random or if they have been manipulated in some way.
# Let’s use this to test the random numbers generated by R.
# The below code simulates rolling a dice 100 times and recording the results.
# Run this code in R to conduct your own experiment.
dice.rolls=sample(seq(1,6), 100, replace=TRUE) ##roll a dice 100 times
table(dice.rolls)

# Now perform a χ2 test on your results.
# What can you conclude from your test?
  
# Notice, the χ2 test can be used to discover when a supposedly random process is being manipulated.

dice.rolls <- sample(seq(1,6), 100, replace = TRUE)
table(dice.rolls)

chisq.test(table(dice.rolls))
# The large p-value indicates that there is no difference between the groups.


#*** 2. ----
# Mendel Peas:
# In genetics the χ2 test is often used to detect when genes violate Mendel’s principle of independent assortment in the study of genetics.
# In the mid 1800’s Gregor Mendel came up with the modern theory of genetics using pea plants.
# Using his theory he was able to predict the percentage of his pea plants that would have certain characteristics.
# A table of his predicted fraction and the data he collected is shown below:
# Phenotype 	      Observed 	Expected Frequency
# Yellow round 	      315 	    9/16
# Yellow wrinkled 	  101 	    3/16
# Green round 	      108 	    3/16
# Green wrinkled 	    32 	      1/16
# H0: The generation is comprised of four phenotypes in the proportions predicted by Mendelian genetics.
# Ha: The generation is NOT comprised of the four phenotypes in the proprtions predicted by Mendelian genetics.

# You can make a table for mendel’s data using the below command in R:
mendel.table=as.table(c(YR=315, YW=101, GR=108, GW=32))

# + Now run a χ2 test with the null hypothesis in the chisq.test command.
#   Interpret your results.
# + What is the logical issue with using a χ2 test in this manner? Have we really proven Mendel’s theory?

mendel.table <- as.table(c(YR = 315, YW = 101, GR = 108, GW = 32))

chisq.test(mendel.table, p = c(9/16, 3/16, 3/16, 1/16))
# The large p-value indicates that can't reject H0.

# No issues. Yes?


#*** 3. ----
# Young People Survey:
# Load the young people survey data from my package with the command.
# Run a χ2 test to look for a relationship between the Young_People_Survey$Adrenaline sports`column and theYoung_People_Survey$Snakes` column.
# Interpret your results.
table(Young_People_Survey$`Adrenaline sports`, Young_People_Survey$Snakes)

chisq.test(table(Young_People_Survey$`Adrenaline sports`, Young_People_Survey$Snakes))

# The small p-value indicates that we should reject the null hypothesis that the are two columns are unrelated.